language: php

php:
  - 7.1
  - 7.2

before_script:
  - cp .env.travis .env
  - mysql -e 'create database spendy_test;'
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - php artisan key:generate
  - php artisan migrate

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
